/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Pdf */
        post: operations["upload_pdf_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Analysis */
        post: operations["create_analysis_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{analysis_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Events */
        get: operations["analysis_events_v1_analyses__analysis_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{analysis_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Analysis */
        post: operations["cancel_analysis_v1_analyses__analysis_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{analysis_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_v1_analyses__analysis_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider Settings */
        get: operations["get_provider_settings_v1_settings_get"];
        /** Put Provider Settings */
        put: operations["put_provider_settings_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Models */
        get: operations["provider_models_v1_providers_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisDepth
         * @enum {string}
         */
        AnalysisDepth: "quick" | "standard" | "deep";
        /** AnalysisReport */
        AnalysisReport: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Scoring Version
             * @default 1.0
             * @constant
             */
            scoring_version: "1.0";
            identity: components["schemas"]["PaperIdentity"];
            profile: components["schemas"]["RubricProfile"];
            /** Language */
            language: string;
            /** Composite Score */
            composite_score: number;
            /** Uncapped Score */
            uncapped_score: number;
            /** Dimensions */
            dimensions: components["schemas"]["DimensionScore"][];
            coverage: components["schemas"]["Coverage"];
            context: components["schemas"]["ContextAssessment"];
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Banners */
            banners: string[];
            /** Limitations */
            limitations: string[];
            /** Audit Trail */
            audit_trail: {
                [key: string]: unknown;
            }[];
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
        };
        /** AnalysisRequest */
        AnalysisRequest: {
            source: components["schemas"]["PaperSource"];
            /** @default standard */
            depth: components["schemas"]["AnalysisDepth"];
            /** Enabled Checks */
            enabled_checks?: string[];
            /** Max Cost Usd */
            max_cost_usd?: number | null;
            /**
             * Sequential
             * @default false
             */
            sequential: boolean;
        };
        /**
         * AnalysisState
         * @enum {string}
         */
        AnalysisState: "queued" | "running" | "completed" | "failed" | "cancelled";
        /** AnalysisStatus */
        AnalysisStatus: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            state: components["schemas"]["AnalysisState"];
            /** Progress */
            progress: number;
            /** Stage */
            stage: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Error */
            error?: string | null;
        };
        /** Body_upload_pdf_v1_uploads_post */
        Body_upload_pdf_v1_uploads_post: {
            /** File */
            file: string;
        };
        /** ContextAssessment */
        ContextAssessment: {
            /**
             * Retracted
             * @default false
             */
            retracted: boolean;
            /**
             * Expression Of Concern
             * @default false
             */
            expression_of_concern: boolean;
            /** Corrections */
            corrections?: string[];
            /** Venue Signals */
            venue_signals?: string[];
            /** Author Conflict Signals */
            author_conflict_signals?: string[];
            /** Metric Notes */
            metric_notes?: string[];
        };
        /** Coverage */
        Coverage: {
            /** Paper */
            paper: number;
            /** Context */
            context: number;
            /** Overall */
            overall: number;
            /** Provisional */
            provisional: boolean;
            /** Limitations */
            limitations?: string[];
        };
        /** DimensionScore */
        DimensionScore: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Weight */
            weight: number;
            /** Score */
            score: number;
            /** Assessed Items */
            assessed_items: number;
            /** Total Items */
            total_items: number;
        };
        /** EvidenceSource */
        EvidenceSource: {
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Publisher */
            publisher?: string | null;
            /**
             * Accessed At
             * Format: date-time
             */
            accessed_at: string;
            /** Identifier */
            identifier?: string | null;
        };
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Rubric Item */
            rubric_item: string;
            /** Title */
            title: string;
            /** Explanation */
            explanation: string;
            severity: components["schemas"]["FindingSeverity"];
            grade: components["schemas"]["RubricGrade"];
            /** Confidence */
            confidence: number;
            /** Paper Spans */
            paper_spans?: components["schemas"]["PaperSpan"][];
            /** External Sources */
            external_sources?: components["schemas"]["EvidenceSource"][];
            /** Affected Conclusions */
            affected_conclusions?: string[];
            /** Counterevidence */
            counterevidence?: string[];
            /** Limitations */
            limitations?: string[];
            /**
             * Critic Disposition
             * @default accepted
             * @enum {string}
             */
            critic_disposition: "accepted" | "revised" | "discarded";
        };
        /**
         * FindingSeverity
         * @enum {string}
         */
        FindingSeverity: "info" | "minor" | "major" | "critical";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaperIdentity */
        PaperIdentity: {
            /** Doi */
            doi?: string | null;
            /** Title */
            title?: string | null;
            /** Authors */
            authors?: string[];
            /** Journal */
            journal?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Fingerprint */
            fingerprint: string;
        };
        /** PaperSource */
        PaperSource: {
            kind: components["schemas"]["PaperSourceKind"];
            /** Value */
            value: string;
        };
        /**
         * PaperSourceKind
         * @enum {string}
         */
        PaperSourceKind: "doi" | "url" | "upload";
        /** PaperSpan */
        PaperSpan: {
            /** Section */
            section?: string | null;
            /** Page */
            page?: number | null;
            /** Quote */
            quote: string;
            /** Start */
            start?: number | null;
            /** End */
            end?: number | null;
        };
        /** ProviderSettingsInput */
        ProviderSettingsInput: {
            /**
             * Base Url
             * Format: uri
             * @default https://api.tokenfactory.nebius.com/v1/
             */
            base_url: string;
            /** Api Key */
            api_key?: string | null;
            /**
             * Clear Api Key
             * @default false
             */
            clear_api_key: boolean;
            /**
             * Planner Model
             * @default
             */
            planner_model: string;
            /**
             * Worker Model
             * @default
             */
            worker_model: string;
            /**
             * Critic Model
             * @default
             */
            critic_model: string;
            /** @default standard */
            default_depth: components["schemas"]["AnalysisDepth"];
            /**
             * Max Concurrency
             * @default 5
             */
            max_concurrency: number;
            /**
             * Sequential Mode
             * @default false
             */
            sequential_mode: boolean;
            /**
             * Max Cost Usd
             * @default 2
             */
            max_cost_usd: number;
            /**
             * Retention Days
             * @default 30
             */
            retention_days: number;
        };
        /** ProviderSettingsView */
        ProviderSettingsView: {
            /**
             * Base Url
             * Format: uri
             */
            base_url: string;
            /** Has Api Key */
            has_api_key: boolean;
            /**
             * Api Key Source
             * @enum {string}
             */
            api_key_source: "encrypted" | "environment" | "missing";
            /** Planner Model */
            planner_model: string;
            /** Worker Model */
            worker_model: string;
            /** Critic Model */
            critic_model: string;
            default_depth: components["schemas"]["AnalysisDepth"];
            /** Max Concurrency */
            max_concurrency: number;
            /** Sequential Mode */
            sequential_mode: boolean;
            /** Max Cost Usd */
            max_cost_usd: number;
            /** Retention Days */
            retention_days: number;
        };
        /**
         * RubricGrade
         * @enum {string}
         */
        RubricGrade: "no_concern" | "minor_concern" | "major_concern" | "critical_concern" | "not_assessed";
        /**
         * RubricProfile
         * @enum {string}
         */
        RubricProfile: "randomized_experiment" | "observational_study" | "qualitative_research" | "systematic_review_meta_analysis" | "diagnostic_prediction" | "computational_ml_modeling" | "common_core";
        /** UploadReceipt */
        UploadReceipt: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sha256 */
            sha256: string;
            /** Bytes */
            bytes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_pdf_v1_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_pdf_v1_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analysis_events_v1_analyses__analysis_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_analysis_v1_analyses__analysis_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_v1_analyses__analysis_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_settings_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSettingsView"];
                };
            };
        };
    };
    put_provider_settings_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderSettingsInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSettingsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_models_v1_providers_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: string;
                        }[];
                    };
                };
            };
        };
    };
}
